CREATE TABLE users(
	id BIGINT AUTO_INCREMENT NOT NULL,
	login VARCHAR(15) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(15) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id)
)ENGINE=InnoDB default charset=utf8;